import type { Category, Provider } from "./types";

// Seed data: lets the app run with zero database configured.
// Once Supabase is wired and seeded, live data takes over automatically.

export const SEED_CATEGORIES: Category[] = [
  { slug: "private-chefs", label: "Private Chefs", icon: "chef", sort: 1 },
  { slug: "drivers", label: "Drivers", icon: "driver", sort: 2 },
  { slug: "house-cleaning", label: "House Cleaning", icon: "cleaning", sort: 3 },
  { slug: "babysitters", label: "Babysitters", icon: "baby", sort: 4 },
  { slug: "boat-services", label: "Boat Services", icon: "boat", sort: 5 },
  { slug: "wellness", label: "Wellness", icon: "wellness", sort: 6 },
  { slug: "handymen", label: "Handymen", icon: "handyman", sort: 7 },
  { slug: "photography", label: "Photography", icon: "photo", sort: 8 },
  { slug: "concierge", label: "Concierge", icon: "concierge", sort: 9 },
  { slug: "tour-guides", label: "Tour Guides", icon: "guide", sort: 10 },
];

const face = (g: string, n: number) => `https://randomuser.me/api/portraits/${g}/${n}.jpg`;
const gal = (seed: string) => `https://picsum.photos/seed/ilha-${seed}/800/600`;

type Raw = Omit<Provider, "category_label" | "category_icon" | "location_slug"> & { category_slug: string };

const RAW: Raw[] = [
  { slug:"maria-santos", name:"Maria Santos", category_slug:"private-chefs", tier:"premium", verified:true,
    photo_url:face("women",44), languages:["Português","English","Español"], service_area:"Vila & Sul da Ilha",
    half_day_rate:400, full_day_rate:700, hourly_rate:90, phone:"+5512991234501", whatsapp:"+5512991234501",
    intro_video_url:null,
    short_desc:"Cozinha de praia autoral com frutos do mar locais, servida na sua casa.",
    long_desc:"Cheguei a Ilhabela há 12 anos vinda de São Paulo e nunca mais quis sair. Cozinho menus de degustação com peixe fresco do dia, banana-da-terra, palmito pupunha e tudo que a ilha oferece. Atendo jantares íntimos, almoços de barco e celebrações em casas de temporada. Levo tudo: ingredientes, equipa e a louça. Você só relaxa.",
    gallery:[gal("chefa"),gal("chefb"),gal("chefc"),gal("chefd")] },
  { slug:"joao-oliveira", name:"João Oliveira", category_slug:"drivers", tier:"premium", verified:true,
    photo_url:face("men",32), languages:["Português","English"], service_area:"Toda a ilha + Continente",
    half_day_rate:300, full_day_rate:520, hourly_rate:70, phone:"+5512991234502", whatsapp:"+5512991234502",
    intro_video_url:null,
    short_desc:"Transfers do aeroporto, passeios pela ilha e motorista privado o dia todo.",
    long_desc:"Sou motorista há 15 anos e conheço cada curva da Estrada da Costa. Faço transfer de São Sebastião e dos aeroportos de São Paulo, tours pelas praias do sul e estou disponível para o que a sua família precisar durante a estadia. Carro climatizado, água gelada e zero pressa.",
    gallery:[gal("cara"),gal("carb"),gal("carc"),gal("card")] },
  { slug:"camila-ferreira", name:"Camila Ferreira", category_slug:"babysitters", tier:"featured", verified:true,
    photo_url:face("women",68), languages:["Português","English"], service_area:"Norte da Ilha",
    half_day_rate:180, full_day_rate:320, hourly_rate:45, phone:"+5512991234503", whatsapp:"+5512991234503",
    intro_video_url:null,
    short_desc:"Babá experiente e carinhosa, formada em pedagogia. Noites e diárias.",
    long_desc:"Trabalho com crianças há 9 anos e sou formada em pedagogia. Cuido dos pequenos enquanto os pais aproveitam um jantar ou um passeio de barco. Brincadeiras na praia, hora do banho, histórias para dormir. Referências de várias famílias que voltam todo ano.",
    gallery:[gal("babya"),gal("babyb"),gal("babyc")] },
  { slug:"ricardo-almeida", name:"Ricardo Almeida", category_slug:"boat-services", tier:"premium", verified:true,
    photo_url:face("men",45), languages:["Português","English","Italiano"], service_area:"Saídas do Perequê",
    half_day_rate:900, full_day_rate:1600, hourly_rate:null, phone:"+5512991234504", whatsapp:"+5512991234504",
    intro_video_url:null,
    short_desc:"Capitão local. Passeios às praias desertas do sul e às ilhas vizinhas.",
    long_desc:"Nasci na ilha e piloto lancha desde menino. Levo você às praias que só se chega de barco — Bonete, Castelhanos, Saco do Sombrio. Mergulho, paradas para almoço e pôr do sol no mar. Lancha para até 10 pessoas, colete para todos e marinheiro a bordo.",
    gallery:[gal("boata"),gal("boatb"),gal("boatc"),gal("boatd")] },
  { slug:"beatriz-costa", name:"Beatriz Costa", category_slug:"wellness", tier:"featured", verified:false,
    photo_url:face("women",12), languages:["Português","English"], service_area:"Atendimento ao domicílio",
    half_day_rate:260, full_day_rate:null, hourly_rate:140, phone:"+5512991234505", whatsapp:"+5512991234505",
    intro_video_url:null,
    short_desc:"Massagem relaxante e terapêutica na sua casa, frente para o mar.",
    long_desc:"Sou massoterapeuta há 7 anos. Levo maca, óleos e uma trilha sonora suave até a sua varanda. Massagem relaxante, desportiva ou drenagem. Ideal depois de um dia de trilha ou de barco. Atendo casais e grupos pequenos com hora marcada.",
    gallery:[gal("spaa"),gal("spab"),gal("spac")] },
  { slug:"lucas-pereira", name:"Lucas Pereira", category_slug:"photography", tier:"featured", verified:false,
    photo_url:face("men",76), languages:["Português","English"], service_area:"Toda a ilha",
    half_day_rate:550, full_day_rate:950, hourly_rate:null, phone:"+5512991234506", whatsapp:"+5512991234506",
    intro_video_url:null,
    short_desc:"Ensaios de família e casais nas praias e cachoeiras da ilha.",
    long_desc:"Fotógrafo de viagem e família. Capturo a sua estadia em Ilhabela — do nascer do sol na praia ao mergulho na cachoeira. Entrego fotos editadas em até 5 dias e uma galeria online para compartilhar. Sei os melhores cantos e as melhores luzes.",
    gallery:[gal("phoa"),gal("phob"),gal("phoc"),gal("phod")] },
  { slug:"ana-rodrigues", name:"Ana Rodrigues", category_slug:"house-cleaning", tier:"standard", verified:false,
    photo_url:face("women",65), languages:["Português"], service_area:"Centro & Vila",
    half_day_rate:150, full_day_rate:260, hourly_rate:40, phone:"+5512991234507", whatsapp:"+5512991234507",
    intro_video_url:null,
    short_desc:"Limpeza caprichada de casas de temporada. Check-in e check-out.",
    long_desc:"Faço a limpeza de casas e apartamentos de temporada há 10 anos. Deixo tudo pronto para os hóspedes chegarem e organizo o check-out. Trabalho com produtos próprios e sou pontual. Atendo também limpeza pesada pós-obra.",
    gallery:[gal("clea"),gal("cleb")] },
  { slug:"pedro-lima", name:"Pedro Lima", category_slug:"handymen", tier:"standard", verified:false,
    photo_url:face("men",22), languages:["Português"], service_area:"Toda a ilha",
    half_day_rate:200, full_day_rate:360, hourly_rate:55, phone:"+5512991234508", whatsapp:"+5512991234508",
    intro_video_url:null,
    short_desc:"Pequenos reparos, elétrica, hidráulica e manutenção de casas.",
    long_desc:"Marido de aluguel da ilha. Resolvo o que aparecer: torneira pingando, tomada queimada, móvel para montar, portão emperrado. Atendo proprietários e administradoras de casas de temporada com agilidade. Orçamento na hora.",
    gallery:[gal("hana"),gal("hanb")] },
  { slug:"sofia-martins", name:"Sofia Martins", category_slug:"concierge", tier:"premium", verified:true,
    photo_url:face("women",29), languages:["Português","English","Français"], service_area:"Concierge para toda a ilha",
    half_day_rate:500, full_day_rate:850, hourly_rate:120, phone:"+5512991234509", whatsapp:"+5512991234509",
    intro_video_url:null,
    short_desc:"Concierge pessoal: reservas, passeios, chef, barco — organizo tudo.",
    long_desc:"Cuido da sua estadia de ponta a ponta. Reservo restaurantes, organizo passeios de barco, contrato chef e babá, faço o mercado antes da chegada e resolvo imprevistos. Penso no detalhe para a sua família só aproveitar. Falo três idiomas.",
    gallery:[gal("cona"),gal("conb"),gal("conc")] },
  { slug:"gabriel-souza", name:"Gabriel Souza", category_slug:"tour-guides", tier:"featured", verified:false,
    photo_url:face("men",64), languages:["Português","English"], service_area:"Trilhas & Cachoeiras",
    half_day_rate:280, full_day_rate:480, hourly_rate:null, phone:"+5512991234510", whatsapp:"+5512991234510",
    intro_video_url:null,
    short_desc:"Guia de trilhas credenciado. Cachoeiras, mirantes e Mata Atlântica.",
    long_desc:"Guia de turismo credenciado e apaixonado pela Mata Atlântica. Conduzo trilhas para todos os níveis — da cachoeira fácil ao Pico do Baepi. Conto a história e a natureza da ilha pelo caminho. Levo lanche, água e muita segurança.",
    gallery:[gal("guia"),gal("guib"),gal("guic")] },
  { slug:"larissa-gomes", name:"Larissa Gomes", category_slug:"private-chefs", tier:"standard", verified:false,
    photo_url:face("women",90), languages:["Português","English"], service_area:"Norte da Ilha",
    half_day_rate:320, full_day_rate:560, hourly_rate:75, phone:"+5512991234511", whatsapp:"+5512991234511",
    intro_video_url:null,
    short_desc:"Comida caseira brasileira e café da manhã para a casa toda.",
    long_desc:"Cozinho a comida de casa que dá saudade: feijoada no sábado, peixe na telha, café da manhã reforçado para encarar o dia de praia. Atendo grupos e famílias grandes em casas de temporada. Faço também o mercado.",
    gallery:[gal("chee"),gal("chef2")] },
  { slug:"thiago-barbosa", name:"Thiago Barbosa", category_slug:"drivers", tier:"standard", verified:false,
    photo_url:face("men",3), languages:["Português"], service_area:"Transfers Aeroporto",
    half_day_rate:280, full_day_rate:null, hourly_rate:65, phone:"+5512991234512", whatsapp:"+5512991234512",
    intro_video_url:null,
    short_desc:"Transfer pontual de Guarulhos e Congonhas direto para a balsa.",
    long_desc:"Especialista em transfer aeroporto. Busco em Guarulhos ou Congonhas e levo com tranquilidade até a balsa de São Sebastião, acompanhando a travessia. Monitoro o seu voo e ajusto o horário se atrasar. Veículo confortável para malas e família.",
    gallery:[gal("tra"),gal("trb")] },
];

const CAT_BY_SLUG = Object.fromEntries(SEED_CATEGORIES.map((c) => [c.slug, c]));

export const SEED_PROVIDERS: Provider[] = RAW.map((r) => ({
  ...r,
  id: r.slug,
  category_label: CAT_BY_SLUG[r.category_slug]?.label ?? r.category_slug,
  category_icon: CAT_BY_SLUG[r.category_slug]?.icon ?? "concierge",
  // Seed providers are all Ilhabela, so they only surface on /ilhabela.
  location_slug: "ilhabela",
}));
